Update Update-secret.yml

diff --git a/.github/workflows/Update-secret.yml b/.github/workflows/Update-secret.yml
--- a/.github/workflows/Update-secret.yml
+++ b/.github/workflows/Update-secret.yml
@@ -1,23 +1,37 @@
-name: Update Azure Service Principal
+name: Manage AzKV Secrets
 
 on:
-  push:
-    branches:
-      - main
+  workflow_dispatch:
+    inputs:
+      secretName:
+        description: 'Secret Name'
+        required: true
+      secretValue:
+        description: 'Secret Value'
+        required: true
+      keyvaultName:
+        description: 'Keyvault Name'
+        required: true
 
 jobs:
-  update-service-principal:
+  update-kv-secret:
     runs-on: ubuntu-latest
     steps:
-    - name: Checkout code
-      uses: actions/checkout@v2
-
     - name: Login to Azure
       uses: azure/login@v1
       with:
         creds: ${{ secrets.AZURE_CREDENTIALS }}
 
-    - name: Update Service Principal
+    - id: check-secret
+      name: Check Secret
       run: |
-        # Your command to update the service principal
-        az ad sp update --id <Service-Principal-Id> --set <Properties>
+        secret=$(az keyvault secret list --vault-name ${{ github.event.inputs.keyvaultName }} --query "[?name=='${{ github.event.inputs.secretName }}']" -o tsv)
+        if [ -z "$secret" ]; then
+          echo "Secret not found"
+          exit 1
+        fi
+
+    - name: Update Secret
+      if: ${{ success() }}
+      run: |
+        az keyvault secret set --vault-name ${{ github.event.inputs.keyvaultName }} --name ${{ github.event.inputs.secretName }} --value ${{ github.event.inputs.secretValue }}
